#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

nitrogen --restore &
~/.config/polybar/launch.sh
nm-applet &
picom -b &
dunst &
pcloud &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         2
bspc config window_gap           4

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule --add Chromium          desktop='^1'
bspc rule --add Pcmanfm           desktop='^3'
bspc rule --add 1Password         state=floating
